name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    
    - name: Run tests
      run: |
        python test_cloc.py
    
    - name: Test cloc-py functionality
      run: |
        python cloc_py.py --help
        python cloc_py.py . --format json
        python cloc_py.py . --format csv
        python cloc_py.py . --by-file | head -10
    
    - name: Test installation
      run: |
        pip install -e .
        cloc-py --help 